src/MyPortfolio/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyPortfolio.Contexts;
using MyPortfolio.Models.Blog;
using Microsoft.Extensions.PlatformAbstractions;

namespace MyPortfolio.Controllers
{
    public class BlogsController : Controller
    {
        private readonly BloggingContext _context;

        public BlogsController(BloggingContext context)
        {
            _context = context;    
        }

        // GET: Blogs
        public async Task<IActionResult> Index(Tags tag, string currentTag)
        {
            var allPostsInCurrentTag = GetAllPostsInCurrentTag(tag);
            switch (tag)
            {
                case Tags.DSP2017:
                    allPostsInCurrentTag = await GetAllPostsInCurrentTagAsync(Tags.DSP2017);
                    break;

                case Tags.CSHARP:
                    allPostsInCurrentTag = await GetAllPostsInCurrentTagAsync(Tags.CSHARP);
                    break;

                case Tags.QA:
                    allPostsInCurrentTag = await GetAllPostsInCurrentTagAsync(Tags.QA);
                    break;

                default:
                    allPostsInCurrentTag = GetAllPostsInCurrentTag(tag);
                    break;
            } 

            return View(allPostsInCurrentTag);
        }

        private async Task<List<Post>> GetAllPostsInCurrentTagAsync(Tags tag)
        {
            return await Task.Run(() => GetAllPostsInCurrentTag(tag));
        }


        private List<Post> GetAllPostsInCurrentTag(Tags tag)
        {
            List<Post> allPostsInCurrentTag = new List<Post>();
            //Eagerloading
            var postsWithTags = _context.Posts.Include(m => m.Tags);
            foreach (Post post in postsWithTags)
            {
                if (post.Tags != null)
                {
                    foreach (Tag t in post.Tags)
                    {
                        if (t != null && t.TagCategory.Equals(tag))
                        {
                            allPostsInCurrentTag.Add(post);
                        }
                    }
                }
            }
            return allPostsInCurrentTag;
        }
        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .SingleOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,Url")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.SingleOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlogId,Url")] Blog blog)
        {
            if (id != blog.BlogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.BlogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .SingleOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.SingleOrDefaultAsync(m => m.BlogId == id);
            _context.Blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.BlogId == id);
        }
    }
}

src/MyPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>

    <!-- Mobile Data -->
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <environment names="Development">
        <link href="~/css/jquery.fancybox.css" rel="stylesheet" />
        <!-- Twitter Bootstrs CSS -->
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <!-- Ionicons Fonts Css -->
        <link href="~/css/ionicons.min.css" rel="stylesheet" />
        <!-- animate css -->
        <link href="~/css/animate.css" rel="stylesheet" />
        <!-- Hero area slider css-->
        <link href="~/css/slider.css" rel="stylesheet" />
        <!-- owl craousel css -->
        <link href="~/css/owl.carousel.css" rel="stylesheet" />
        <link href="~/css/owl.theme.css" rel="stylesheet" />
        <!-- template main css file -->
        <link href="~/css/main.css" rel="stylesheet" />
        <!-- responsive css -->
        <link href="~/css/responsive.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" />
        <link href="~/css/video.css" rel="stylesheet" />

    </environment>
    <environment names="Staging,Production">
         <link href="~/css/jquery.fancybox.css" rel="stylesheet" />
        <!-- Twitter Bootstrs CSS -->
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <!-- Ionicons Fonts Css -->
        <link href="~/css/ionicons.min.css" rel="stylesheet" />
        <!-- animate css -->
        <link href="~/css/animate.css" rel="stylesheet" />
        <!-- Hero area slider css-->
        <link href="~/css/slider.css" rel="stylesheet" />
        <!-- owl craousel css -->
        <link href="~/css/owl.carousel.css" rel="stylesheet" />
        <link href="~/css/owl.theme.css" rel="stylesheet" />
        <!-- template main css file -->
        <link href="~/css/main.css" rel="stylesheet" />
        <!-- responsive css -->
        <link href="~/css/responsive.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" />
        <link href="~/css/video.css" rel="stylesheet" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <header id="top-bar" class="navbar-fixed-top animated-header">
        <div class="container">
            <!-- main menu -->
            <nav class="nav navbar-nav navbar-right" role="navigation">
                <div class="main-menu">
                    <ul class="nav navbar-nav navbar-right">
                        <li id="homeNavbar"><a class="animated-header wow smooth-scroll" data-wow-delay=".9s" href="#hero-area" data-section="#hero-area">@ViewData["home"]</a></li>
                        <li id="aboutNavbar"><a class="animated-header wow smooth-scroll" data-wow-delay=".9s" href="#about" data-section="#about">@ViewData["about"]</a></li>                      
                        <li id="contactNavbar"><a class="animated-header wow smooth-scroll" data-wow-delay=".9s" href="#call-to-action" data-section="#call-to-action">@ViewData["contact"]</a></li>
                        <li id="blogNavbar"><a asp-controller="Blogs" asp-action="Index" data-wow-delay=".9s">Blog</a></li>
                        @*<li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle" role="button" aria-expanded="false" id="dropdownStandard">Język<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li id="PL"><a href="#">PL</a></li>
                                <li id="ENG"><a href="#">ENG</a></li>
                            </ul>
                        </li>*@                      
                    </ul>
                </div>
            </nav>
            <!-- /main nav -->
        </div>
    </header>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer id="footer">
            <div class="container">
                <div class="col-md-4">
                    <p>&copy; @ViewData["Title"] - Portfolio</p>
                </div>
                <div class="col-md-4">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
                <div class="col-md-4">
                    <ul class="social">
                        <li>
                            <a href="https://www.facebook.com/marcin.stanek.90" class="Facebook">
                                <i class="ion-social-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/marcin-stanek-524485114?trk=nav_responsive_tab_profile_pic" class="Linkedin">
                                <i class="ion-social-linkedin"></i>
                            </a>
                        </li>
                    </ul>
                    </div>
                </div>        
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/jquerry-fancybox/dist/jquery.fancybox.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/slider.js"></script>
        <script src="~/js/wow.min.js"></script>
        <script src="~/js/main.js"></script>
        <script src="~/js/hidden.js"></script>
        <script src="~/js/bootstrap-notify.js"></script>
        <script src="~/js/video.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/jquerry-fancybox/dist/jquery.fancybox.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/slider.js"></script>
        <script src="~/js/wow.min.js"></script>
        <script src="~/js/main.js"></script>
        <script src="~/js/hidden.js"></script>
        <script src="~/js/bootstrap-notify.js"></script>
        <script src="~/js/video.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/MyPortfolio/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @Localizer[@ViewData["footerLanguage"] + ":"] <select name="culture"
                                        asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
        <button type="submit" class="btn btn-default btn-xs">@ViewData["footerButton"]</button>

    </form>
</div>  